[tool.briefcase]
project_name = "codecrafty"
bundle = "com.codecrafty.ide"
version = "0.0.1"
url = "https://github.com/dimkauzh/codecrafty/"
license = "MIT license"
author = "Dima Marhitych (@dimkauzh)"
author_email = "uzhdimka@gmail.com"

[tool.briefcase.app.codecrafty]
formal_name = "codecrafty"
description = "A super fast and extensible code editor written in Python"
long_description = """codecrafty is a super fast and extensible code editor written in Python and powered by Toga + Briefcase. It's designed to be an enjoyable and educational project, where you can dive into the world of code and unleash your creativity!"""

icon = "src/codecrafty/resources/codecrafty"
sources = [
    "src/codecrafty",
]
test_sources = [
    "tests",
]

requires = [
]
test_requires = [
    "pytest",
]

[tool.briefcase.app.codecrafty.macOS]
requires = [
    "std-nslog~=1.0.0"
]

[tool.briefcase.app.codecrafty.linux]
requires = [
]

[tool.briefcase.app.codecrafty.linux.system.debian]
system_requires = [
]

system_runtime_requires = [
]

[tool.briefcase.app.codecrafty.linux.system.rhel]
system_requires = [
]

system_runtime_requires = [
]

[tool.briefcase.app.codecrafty.linux.system.arch]
system_requires = [
]

system_runtime_requires = [
]

[tool.briefcase.app.codecrafty.linux.appimage]
manylinux = "manylinux2014"

system_requires = [
]
linuxdeploy_plugins = []

[tool.briefcase.app.codecrafty.linux.flatpak]
flatpak_runtime = "org.freedesktop.Platform"
flatpak_runtime_version = "22.08"
flatpak_sdk = "org.freedesktop.Sdk"

[tool.briefcase.app.codecrafty.windows]
requires = []
